---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
  name: tpcc
  namespace: default 
  labels:
    name: tpcc
spec:
  replicas: 1
  template: 
    metadata:
      labels: 
        name: tpcc
    spec:
      containers:
        - resources:
            limits:
              cpu: 0.3
          name: tpcc
          image: ksatchit/custom-tpcc:ci-1
